### ISSUE TITLE
gprc  issue

### ISSUE THREAD

**Issue by s0gemaker** [angular-university/stripe-course#24]
npm install gives following stack trace...
`In file included from /usr/include/string.h:495,
                 from ../deps/grpc/third_party/nanopb/pb.h:68,
                 from ../deps/grpc/third_party/nanopb/pb_decode.h:9,
                 from ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:21:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’ at ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:74:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 128 equals destination size
 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:520: Release/obj.target/grpc/deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.o] Error 1
make: Leaving directory '/home/syeda/stripe-course/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/syeda/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
gyp ERR! command "/home/syeda/.nvm/versions/node/v14.17.4/bin/node" "/home/syeda/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
"--fallback-to-build" "--library=static_library" "--module=/home/syeda/stripe-course/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node" "--modu
le_name=grpc_node" "--module_path=/home/syeda/stripe-course/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc" "--napi_version=8" "--node_abi_napi=napi" "--na
pi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/syeda/stripe-course/node_modules/grpc
gyp ERR! node -v v14.17.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/syeda/.nvm/versions/node/v14.17.4/bin/node /home/syeda/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/node
-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/syeda/stripe-course/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/g
rpc_node.node --module_name=grpc_node --module_path=/home/syeda/stripe-course/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=8 --node_abi_na
pi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/syeda/stripe-course/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
node-pre-gyp ERR! command "/home/syeda/.nvm/versions/node/v14.17.4/bin/node" "/home/syeda/stripe-course/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-t
o-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/syeda/stripe-course/node_modules/grpc
node-pre-gyp ERR! node -v v14.17.4
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/home/syeda/.nvm/versions/node/v14.17.4/bin/node /home/syeda/.nvm/versions/node/v14.17.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fa
llback-to-build --library=static_library --module=/home/syeda/stripe-course/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grp
c_node --module_path=/home/syeda/stripe-course/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=8 --node_abi_napi=napi --napi_build_version=0
--node_napi_label=node-v83' (1)
npm WARN @angular/fire@5.4.2 requires a peer of @angular/common@>=6.0.0 <9 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.4.2 requires a peer of @angular/core@>=6.0.0 <9 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.4.2 requires a peer of @angular/platform-browser@>=6.0.0 <9 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/fire@5.4.2 requires a peer of @angular/platform-browser-dynamic@>=6.0.0 <9 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN firebaseui@4.8.1 requires a peer of firebase@>=8.2.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

**Comment by s0gemaker** [comment]
resolved

**Comment by aj07mm** [comment]
how that was resolved @s0gemaker ?

**Comment by s0gemaker** [comment]
I was using wrong node version.
